START
dataType mc
###MVA Flags###
createMVATree 0
readMVA 0
MVAnetwork BDT
MVAxmlFile /home/gsaha/DelphesHiggsProject/TMVAClassification_BDT.weights.xml
mvaInputFile signal_h2z_FTree.root
###############
lumiWtList xsec=0.0000852545 intLumi=3000000 nevents=100000
histFile  signal_h2z.root
maxEvent -1
###############
#Cuts
muonCutList eta=2.4 pt=10. iso=0.15
electronCutList pt=10. eta=2.5 iso=0.11
tauCutList eta=2.4 pt=20. dz=0.2 muVeto=0.5 eleVeto=0.5 isol=0.5
jetCutList eta=2.4 pt=20 mindRlep=0.1 
photonCutList pt=10 eta=2.4 isol=1.8 dRmin=0.5 dRovEt2=0.012
evselCutList hLepPtMin=40. maxJetPt=60. maxMET=200. minDRLP=0.2
###############
#inputFiles
inputFile /media/lacie8tby/Exotic/Delphes/Signal/pp_h2z/pp_h2z_0.root
inputFile /media/lacie8tby/Exotic/Delphes/Signal/pp_h2z/pp_h2z_1.root
inputFile /media/lacie8tby/Exotic/Delphes/Signal/pp_h2z/pp_h2z_2.root
inputFile /media/lacie8tby/Exotic/Delphes/Signal/pp_h2z/pp_h2z_3.root
inputFile /media/lacie8tby/Exotic/Delphes/Signal/pp_h2z/pp_h2z_4.root
inputFile /media/lacie8tby/Exotic/Delphes/Signal/pp_h2z/pp_h2z_5.root
inputFile /media/lacie8tby/Exotic/Delphes/Signal/pp_h2z/pp_h2z_6.root
inputFile /media/lacie8tby/Exotic/Delphes/Signal/pp_h2z/pp_h2z_7.root
inputFile /media/lacie8tby/Exotic/Delphes/Signal/pp_h2z/pp_h2z_8.root
inputFile /media/lacie8tby/Exotic/Delphes/Signal/pp_h2z/pp_h2z_9.root
readGenInfo 0
dumpGenInfo 0
eventId 1 895751 20
END
